### ISSUE TITLE
Roto Blitter bug

### ISSUE THREAD

**Issue by chezinut** [grandchild/AVS-File-Decoder#6]
Presets with Roto Blitter won't to load... Decoder freezes 

![avs file decoder](https://f.cloud.github.com/assets/1907260/1749811/80eca61e-6542-11e3-98be-3e85a725e0a4.png)

**Comment by grandchild** [comment]
The new version 1.0.0 shouldn't do this anymore, however the demo website is not updated yet..
@idleberg, would you want to update that?

**Comment by grandchild** [comment]
Deferred to #8.

**Comment by idleberg** [comment]
> @idleberg, would you want to update that?

soon(tm)
