### ISSUE TITLE
Cannot decode old 0.2 AVS

### ISSUE THREAD

**Issue by AloisMahdal** [grandchild/AVS-File-Decoder#7]
I just tried to decode bunch of AVS files I found in my attic.  All decoded fine except for one.  (By "fine" I mean I got sensible JSON, although I did not have opportunity to test them).

All were made by Winamp, although I don't remember version (possibly they could have been started by 2.x and retouched by 3.x or 5.x).  Also I don't remember if there was anything special about this particular file.

So either the file is corrupted, or maybe there's a bug somewhere?  Since they unzipped just fine, and none of them looks garbled, I guess the latter.  So if you want to check it out, I have uploaded them all to [Github](https://github.com/AloisMahdal/nostavs); the failing one is [avs/propan-butan_3_-_heavy_flies.avs](https://github.com/AloisMahdal/nostavs/raw/master/avs/propan-butan_3_-_heavy_flies.avs).

**Comment by grandchild** [comment]
This converts fine now for me with 1.0.0.

> soon

:wink:

[propan-butan_3_-_heavy_flies.txt](https://github.com/grandchild/AVS-File-Decoder/files/1350413/propan-butan_3_-_heavy_flies.txt)
